package rand

import "webtyp.com/base64"

// DefaultSecretBytes is the entropy size of a secret generated by Secret:
// 32 bytes = 256 bits, equivalent to an HS256 key.
const DefaultSecretBytes = 32

// Bytes returns n cryptographically random bytes. Returns an error if n <= 0
// or if the random generator fails.
func Bytes(n int) ([]byte, error) {
	if n <= 0 {
		return nil, ErrInvalidLength
	}
	buf := make([]byte, n)
	if err := Read(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Secret returns DefaultSecretBytes random bytes URL-safe base64 encoded.
// It is designed for generating session IDs, OAuth states, or client secrets.
func Secret() (string, error) {
	return SecretN(DefaultSecretBytes)
}

// SecretN returns n random bytes URL-safe base64 encoded.
// Non-positive n defaults to DefaultSecretBytes.
func SecretN(n int) (string, error) {
	if n <= 0 {
		n = DefaultSecretBytes
	}
	buf, err := Bytes(n)
	if err != nil {
		return "", err
	}
	return base64.URLEncode(buf), nil
}
